package com.nortal.treasurehunt.enums;

public enum ErrorCode {
  UNEXPECTED_ERROR,
  INVALID_INPUT,
  GAME_EXISTS,
  TEAM_EXISTS,
  TEAM_COMPLETED,
  INVALID_GAME_STATE,
  INVALID_MEMBER,
  INVALID_GAME,
  INVALID_TEAM,
  INVALID_CHALLENGE,
  CHALLENGE_ALREADY_STARTED,
  CHALLENGE_NOT_STARTED,
  CHALLENGE_COMPLETED,
  CHALLENGE_NOT_IN_RANGE,
  UNAUTHORIZED_MEMBER;
}
