package com.nortal.treasurehunt.enums;

public enum ErrorCode {
  UNEXPECTED_ERROR,
  GAME_EXISTS,
  TEAM_EXISTS,
  INVALID_MEMBER,
  INVALID_GAME,
  INVALID_TEAM,
  INVALID_TEAM_MEMBER,
  INVALID_TOKEN,
  CHALLENGE_NOT_STARTED,
  CHALLENGE_COMPLETED,
  WRONG_CHALLENGE;
}
